version: "3.8"

services:
  web:
    build: .
    command: uvicorn src.main:app --reload --workers 4 --host 0.0.0.0 --port 8000
    volumes:
      - ${PWD}/src/:/usr/src/app/src/
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres@localhost:5432/uptime_db

    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=uptime
      - POSTGRES_PASSWORD=mohamed98
      - POSTGRES_DB=uptime_db

    ports:
      - "5433:5432"

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'


  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3002:3002"
    volumes:
      - ${PWD}/grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/prometheus_data
  grafana_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ${PWD}/grafana_data
  postgres_data:

networks:
  default: 
    name: uptime
